# k8s deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: labgke
  labels:
    app: labgke
spec:
  replicas: 2
  selector:
    matchLabels:
      app: labgke
      tier: web
  template:
    metadata:
      labels:
        app: labgke
        tier: web
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP

      - name: myapp2
        image: gcr.io/impacta-turma-4-312421/myfirstapp:2.1
        env:
          - name: MESSAGE
            value: "Rafael diz: :) Nova mensagem de validação. v7"
          - name: REDIS_HOST
            value: "localhost"
        ports:
        - containerPort: 80